Refactor notebooks
StatCan/jupyter-notebooks pull request #43
Opened 2021-07-02 15:28 UTC by rohank07

Add `creds['MINIO_URL'].startswith('https')` to handle https minio url

2021-07-15 19:34 UTC, Jose-Matsuda requested changes
few small things and just a reminder to apply marberts suggestion to the one file as well.

2021-07-15 19:34 UTC, Jose-Matsuda commented on self-serve-storage/R/daaas_storage.R
> +        "AWS_DEFAULT_REGION" = "",
Just a reminder to apply marberts suggestion here if needed.

2021-07-16 15:02 UTC, rohank07 commented on querySQL/daaas_storage_boto3.py
> +    HOST = d['MINIO_URL']
Removed the extra variable.

2021-07-19 19:10 UTC, Jose-Matsuda approved these changes
lgtm

2021-07-19 22:20 UTC, merged